// Quote data for sayings.txt
// One object per saying: { author, saying }
const QUOTES = [
  { author: "Abigail", saying: "I'm definitely a magician" },
  { author: "Ben D", saying: "I genuinely think climbing and death metal conflict" },
  { author: "Ben D", saying: "It sounds like someone choking a wookie" },
  { author: "Ben D", saying: "It was like a koala pissing directly into your mouth" },
  { author: "Ben T", saying: "If I was a millionaire I'd buy a massive space and just watch otters" },
  { author: "Ben T", saying: "Have you seen that infinity gauntlet dildo?" },
  { author: "Ben T", saying: "I’ll optimise you in a minute" },
  { author: "Ben T", saying: "I love a good bruise" },
  { author: "Ben T", saying: "Did you ever listen to Ultraspank?" },
  { author: "Cameron", saying: "You can't cmd+r to trance" },
  { author: "Chris L", saying: "Move transition point of right ear" },
  { author: "Chris L", saying: "Gromit ears still isn’t in master" },
  { author: "Chris L", saying: "Looks like a horrible game of tetris" },
  { author: "Chris L", saying: "Ears update: Aardman still approving" },
  { author: "Chris L", saying: "What are these men doing" },
  { author: "Chris L", saying: "Grizzly bear is mad" },
  { author: "Chris L", saying: "We measured it with Todd's skirts" },
  { author: "Chris L", saying: "I feel like this big buck bunny video has followed me throughout my dev career" },
  { author: "Chris L", saying: "Claw the lock" },
  { author: "Chris L", saying: "Who the fuck has a palm pilot" },
  { author: "Chris L", saying: "Think I’m going to partially degrade soon" },
  { author: "Chris L", saying: "Can’t see the beans" },
  { author: "Chris L", saying: "How big is Simon's big toe to the nearest 2mm" },
  { author: "Colin", saying: "I do like MSG" },
  { author: "Colin", saying: "Anyone want a salty herring?" },
  { author: "Mikalai", saying: "Ok, Simon. You are not allowed to touch soft balls anymore" },
  { author: "Mikalai", saying: "Nick, have you heard of NWA?" },
  { author: "Mikalai", saying: "Are you reviewing yourself?" },
  { author: "Mikalai", saying: "I don't want to make decisions. I want to dance!" },
  { author: "Mikalai", saying: "Hey, don’t touch my jobs!" },
  { author: "Mikalai", saying: "I have no idea what you are doing, but I’m approving" },
  { author: "Mikalai", saying: "Google is wrong" },
  { author: "Mikalai", saying: "Your dirty bag on my table is not acceptable" },
  { author: "Mikalai", saying: "Hello. I’m here to kill jQuery" },
  { author: "Mikalai", saying: "Who the fuck you think we are, Simon? We are the nicest people in this cruel word!" },
  { author: "Mikalai", saying: "Not so quick, cowboy" },
  { author: "Mikalai", saying: "You created a very stupid conflict" },
  { author: "Nick L", saying: "Anyone wearing a russian hat is russian" },
  { author: "Nick L", saying: "When it gets fucked, it’s always impossible to unfuck it" },
  { author: "Nick L", saying: "That table is as flat as something that isn’t flat" },
  { author: "Nick L", saying: "It's like local local rather than local local" },
  { author: "Nick L", saying: "Our servers are so fragile. I just uploaded favicons and it broke the server" },
  { author: "Nick L", saying: "Hover on my penguin" },
  { author: "Nick L", saying: "Front-end wouldn’t be fun if you knew it all really" },
  { author: "Nick L", saying: "Everything looks so good in Sketch, it’s dangerous" },
  { author: "Nick L", saying: "Do you ever find that copy and paste from chrome just doesn’t work?" },
  { author: "Nick L", saying: "Lots of little sausages" },
  { author: "Nick L", saying: "Iran are favourites, right?" },
  { author: "Nick L", saying: "I’m not sure I trust lighthouse" },
  { author: "Nick L", saying: "Every is now css grid" },
  { author: "Nick L", saying: "What is my blob" },
  { author: "Nick L", saying: "I find it really hard not to troll public channels" },
  { author: "Nick L", saying: "Just going to eject and write some java man" },
  { author: "Nick L", saying: "What you said, sounds like what I said" },
  { author: "Nick L", saying: "I just installed husky lint-staged" },
  { author: "Nick L", saying: "Chimney is such a weird word, sounds like it should be chimley" },
  { author: "Nick L", saying: "My cats have bigger claws than any of them" },
  { author: "Nick L", saying: "I can’t see past the pepper juice on my screen" },
  { author: "Nick L", saying: "Nesta was globb" },
  { author: "Nick L", saying: "My eyes have light bulbs in" },
  { author: "Nick L", saying: "Those pink things are scary looking" },
  { author: "Nick L", saying: "Maxing out the bongo on the autobahn" },
  { author: "Nick L", saying: "This would be easier with 3 hands, really" },
  { author: "Nick L", saying: "Could just be my eyes malfunctioning" },
  { author: "Nick L", saying: "Hmm this doesn’t even work" },
  { author: "Nick L", saying: "Smell releaser v1.33.7" },
  { author: "Nick L", saying: "Subtle korma" },
  { author: "Nick L", saying: "They should put some actual bears in the bear pit, that would make it a lot nicer" },
  { author: "Nick L", saying: "Anyone have a spare usb finger warmer?" },
  { author: "Nick L", saying: "Or coat the pole in vaseline" },
  { author: "Nick L", saying: "Why do we have elves" },
  { author: "Simon", saying: "It’s a puller downer for sure" },
  { author: "Simon", saying: "Like areola but different" },
  { author: "Simon", saying: "Getting laminated later" },
  { author: "Simon", saying: "How quick is percy?" },
  { author: "Simon", saying: "I have to say it’s rare for me to look at its bottom" },
  { author: "Simon", saying: "Like being in an iframe 24/7" },
  { author: "Simon", saying: "That’s why I always have a summer dress on underneath" },
  { author: "Simon", saying: "That knob would get in my way" },
  { author: "Todd", saying: "It's all just a bit messy" },
  { author: "Todd", saying: "Turns out gifs are inadequate for proper communication" },
  { author: "Todd", saying: "I’m currently confused but know exactly what’s going on" },
  { author: "Tomasz", saying: "Do you think nsa employs css wizards" },
  { author: "Tomasz", saying: "Dont worry, james already resourced me for the next 5 years" },
  { author: "Chris L", saying: "One arm buzzing, the other laminated" },
  { author: "Nick L", saying: "If you do any hangouts it’ll look like you’re working from a prison" },
  { author: "Thibaud", saying: "How often do you use gitlab and how often are you pissed off at it?" },
  { author: "Nick L", saying: "ARGHHHHH it’s linted my html" },
  { author: "Nick L", saying: "Thibaud, aka captain hook" },
  { author: "Thibaud", saying: "I didn’t even get arrested crossing the border" },
  { author: "Simon", saying: "Nice guys don’t overflow: hidden" },
  { author: "Chris L", saying: "gitlab search is tripe" },
  { author: "Ben T", saying: "Slow, melodic, little bit sludgy but not scuzzy" },
  { author: "Nick L", saying: "We’ll definitely have something" },
  { author: "Chris L", saying: "overflow hidden ftw" },
  { author: "Todd", saying: "It’s just ended up as a hairy elephant" },
  { author: "Ben T", saying: "randomly listened to 3 hours of car driving the other day" },
  { author: "Thibaud", saying: "Lives in desk" },
  { author: "Nick L", saying: "I'll add a notch" },
  { author: "Colin", saying: "Use the nosniff header by default" },
  { author: "Mel", saying: "I call him the Baconator" },
  { author: "Nick L", saying: "mm fermented herring" },
  { author: "Nick L", saying: "is it orange squirrel or purple ufo" },
  { author: "Ben T", saying: "clean but a bit quirky in the legs" },
  { author: "Nick L", saying: "If i was a browser i’d go up and down 6 times" },
  { author: "Nick L", saying: "heard he’s a serial killer in his spare time" },
  { author: "Ben D", saying: "death is real" },
  { author: "Nick L", saying: "are you wearing odour du chum" },
  { author: "Simon", saying: "I don’t even know what project this is" },
  { author: "Nick L", saying: "I just pickled down my shorts" },
  { author: "Thibaud", saying: "aah it's just because I'm stupid" },
  { author: "Chris L", saying: "are you pressing the right button combinations?" },
  { author: "Thibaud", saying: "Welcome to the bridge" },
  { author: "Nick L", saying: "When will Chris stop smelling his trousers" },
  { author: "Chris L", saying: "too much carrot" },
  { author: "Chris L", saying: "have you installed all the pips?" },
  { author: "Nick L", saying: "everything doesn’t work" },
  { author: "Anon", saying: "It’s either django or react native" },
  { author: "Thibaud", saying: "Sorry I'm late and wet" },
  { author: "Chris L", saying: "my banana plants are getting battered" },
  { author: "Nick L", saying: "imagine a fox trying to eat a pineapple" },
  { author: "Nick L", saying: "my gran loves a bit of view source" },
  { author: "Chris L", saying: "the deer will steal it and use it for perfume" },
  { author: "Jenny H", saying: "Tactical bread?" },
  { author: "Chris L", saying: "I’m thinking zen fox next to a light bulb puzzle with a piece missing" },
  { author: "Thibaud", saying: "Do you know what noise zebras make?" },
  { author: "Thibaud", saying: "Do you want to use the sun?" },
  { author: "Thibaud", saying: "'least gross' is a good target" },
  { author: "Nick L", saying: "just had to smash my microphone then write a number on it" },
  { author: "Todd", saying: "It’s not HTML5'ing for some reason" },
  { author: "Thibaud", saying: "In France we call it 'the burial of the boy's life'" },
  { author: "Thibaud", saying: "I googled 'to chug'" },
  { author: "Thibaud", saying: "Can you see the beak?" },
  { author: "Nick S", saying: "This is me" },
  { author: "Chris L", saying: "might actually chain nick to the oval" },
  { author: "Thibaud", saying: "I’m more of the boose and fondue type" },
  { author: "Thibaud", saying: "we can go to Helsinki and all get naked together in a sauna" },
  { author: "Nick L", saying: "he will think your name is burglar" },
  { author: "Tomasz", saying: "new canteen serves tuna salad so that's good." },
  { author: "Jenny H", saying: "he eats hot sauce on porridge" },
  { author: "Chris L", saying: "I probably would sleep in a bin to do that" },
  { author: "Nick L", saying: "must be so he can run away from the bees faster" },
  { author: "Nick L", saying: "My dongle is too heavy" },
  { author: "Todd", saying: "The thing is, frankincense is leading the charge" },
  { author: "Todd", saying: "You might even get to play on a welder" },
  { author: "Ben D", saying: "Christ, you do smell of beer" },
  { author: "Nick L", saying: "my weber started peeling" },
  { author: "Chris L", saying: "Lick Nee" },
  { author: "Chris L", saying: "I’m not a filofax" },
  { author: "Tom S", saying: "I thought someone was practising being an owl" },
  { author: "Anon", saying: "Todd not found." },
  { author: "Chris L", saying: "get the hot toddies on the go" },
  { author: "Colin", saying: "Do you butter your beans?" },
  { author: "Chris L", saying: "imagine being .63 infected" },
  { author: "Simon", saying: "I’m not sure if I'm disgusted or impressed" },
  { author: "Ben E", saying: "Use the intermediate burger" },
  { author: "Nick L", saying: "I just cherry pick to master quick as fuck" },
  { author: "Nick L", saying: "Todd’s got his sausage out" },
  { author: "Nick L", saying: "head of transporting the sausage" },
  { author: "Chris L", saying: "unleash the gorilla" },
  { author: "Nick L", saying: "this is another case where Zorbs are the answer" },
  { author: "Nick L", saying: "please stop super-spreading" },
  { author: "Chris L", saying: "just call me head of aria-atomic" },
  { author: "Thibaud", saying: "Dick is Bob?" },
  { author: "Thibaud", saying: "Dick is Richard?" },
  { author: "Will B", saying: "I used mine for a pihole" },
  { author: "Abigail", saying: "Buttercream not fondant" },
  { author: "Simon", saying: "I have a very egg-shaped head" },
  { author: "Nick L", saying: "You almost feel disabled when you use an android phone" },
  { author: "Nick L", saying: "lorem welshum" },
  { author: "Simon", saying: "Last ditch yank" },
  { author: "Chris L", saying: "deadly yet polite" },
  { author: "Todd", saying: "It's not but it is" },
  { author: "Nick L", saying: "It's like an aquarium tank, but you can eat it" },
  { author: "Abigail", saying: "The brownie food group" },
  { author: "Abigail", saying: "what a pansy" },
  { author: "Abigail", saying: "I think I'm a good seal" },
  { author: "Will H", saying: "It's foamy" },
  { author: "Abigail", saying: "savoury pancakes are like the devils pancakes" },
  { author: "Chris L", saying: "damn you you moreish little tongue shaped crisp" },
  { author: "Ben D", saying: "the code's a bit whiffy" },
  { author: "Chris L", saying: "the bongo bangers" },
  { author: "Chris L", saying: "my nose is already sweating" },
  { author: "Chris L", saying: "reckon they’ll do a spin off of coronation street called coronavirus street?" },
  { author: "Simon", saying: "only if you spread it on his device" },
  { author: "Tomasz", saying: "We'll hip-hop on the slopes" },
  { author: "Todd", saying: "where is here" },
  { author: "Todd", saying: "here is where" },
  { author: "Abigail", saying: "The smaller the baby, the easier it is to take on a plane" },
  { author: "Nick L", saying: "automatically outputs my ascii face on any build" },
  { author: "Cameron", saying: "I guess imma get it from a dutty gabba slag" },
  { author: "Abigail", saying: "just keep adding in the mays" },
  { author: "Tom R", saying: "Don't rub your pubs in my face" },
  { author: "Chris L", saying: "I think i’d rather wrestle fifty bears, blindfolded" },
  { author: "Ben D", saying: "people are too confused to mosh" },
  { author: "Tomasz", saying: "it works sexy" },
  { author: "Simon", saying: "send the lobster" },
  { author: "Chris L", saying: "how much bart can you take" },
  { author: "Simon", saying: "rate my bourbon" },
  { author: "Tomasz", saying: "do you compete with the elders in the family?" },
  { author: "Todd", saying: "suns out guns out" },
  { author: "Anon", saying: "I’d give birth for a year off" },
  { author: "Tomasz", saying: "pipes of peace" },
  { author: "Chris L", saying: "should probably expunge some of my code" },
  { author: "Chris L", saying: "nick in a codebase sandwich" },
  { author: "Abigail", saying: "I have no idea what he's doing" },
  { author: "Simon", saying: "Cameron always brings the fun" },
  { author: "Tomasz", saying: "Sandbox is not real life" },
  { author: "Chris L", saying: "sleep under his nose" },
  { author: "Nick L", saying: "grab my arrow disabler" },
  { author: "Abigail", saying: "professional is boring" },
  { author: "Simon", saying: "I’m confident you can google it more quickly" },
  { author: "Tomasz", saying: "you need patience young man" },
  { author: "Tomasz", saying: "I think I'm just going to show my parma ham" },
  { author: "Abigail", saying: "fancy being a guinea pig chris?" },
  { author: "Chris L", saying: "may as well just buy a cow" },
  { author: "Tom R", saying: "you are the feng to my shui" },
  { author: "Cameron", saying: "I called it dirty-master" },
  { author: "Nick L", saying: "why is black, called black" },
  { author: "Tomasz", saying: "I can hear someone's noises" },
  { author: "Chris L", saying: "just watched as a guy broke in my car whilst eating a big mac" },
  { author: "Tomasz", saying: "I need some oxygen" },
  { author: "Abigail", saying: "hover is the enemy" },
  { author: "Abigail", saying: "this project would be enhanced by place-puppy" },
  { author: "Tomasz", saying: "CTA bingo" },
  { author: "Abigail", saying: "simon would you like to be the broccoli" },
  { author: "Nick L", saying: "you love a good fiddle" },
  { author: "Chris L", saying: "it’s the one and only T O double D" },
  { author: "Tomasz", saying: "thanks for being so agile, like a jaguar" },
  { author: "Abigail", saying: "I'm hoping to make friends with dolphins" },
  { author: "Nick L", saying: "my eyes are still trying to open" },
  { author: "Nick L", saying: "filthy grabber" },
  { author: "Abigail", saying: "you make an excellent note" },
  { author: "Chris L", saying: "do you want to borrow my lobster costume for project kick off" },
  { author: "Tomasz", saying: "Can you stop misspelling Apple Pay or I'll kill you" },
  { author: "Tomasz", saying: "You don't have a beard, you don't understand" },
  { author: "Tomasz", saying: "hey wizards" },
  { author: "Chris L", saying: "oo oat cream" },
  { author: "Chris L", saying: "you just get paid in wands" },
  { author: "Nick L", saying: "person with the biggest wand wins" },
  { author: "Abigail", saying: "I'd love to see a goat on the beach drinking cocktails" },
  { author: "Simon", saying: "this goat needs optimising" },
  { author: "Nick L", saying: "just lie down and spam it into people" },
  { author: "Abigail", saying: "what about a life changing chicken?" },
  { author: "Chris L", saying: "show them your pimped out weapon" },
  { author: "Abigail", saying: "I wouldn't mind hearing a baby goat in the middle of the night" },
  { author: "Tomasz", saying: "I need to move your faces" },
  { author: "Tom D", saying: "I wouldn't fancy my chances against a crow" },
  { author: "Kev", saying: "Where there's blame there's a claim" },
  { author: "Thibaud", saying: "you don’t even need to use english, you can describe things based on their very essence" },
  { author: "Cameron", saying: "sawceee" },
  { author: "Steve S", saying: "I could crush a rocket salad right now" },
  { author: "Simon", saying: "Storage Blob Data Contributor" },
  { author: "Tomasz", saying: "it's a sonarcloud curse" },
  { author: "Tomasz", saying: "I could do a sentence for harassment" },
  { author: "Nick L", saying: "motorised zorb" },
  { author: "Chris L", saying: "underground zorb museum" },
  { author: "Chris L", saying: "tickle your belly" },
  { author: "Nick L", saying: "head of beard growth" },
  { author: "Tomasz", saying: "there's way more PhD around than people think" },
  { author: "Will B", saying: "Snape would teach IE11 cross-compatibility" },
  { author: "Tomasz", saying: "I feel like a monkey in a circus" },
  { author: "Chris L", saying: "open gills on hover" },
  { author: "Nick V", saying: "I’m going to get it out and flop it on the table" },
  { author: "Devon", saying: "Do we need to keep David Cameron or can he be recycled?" },
  { author: "Nick L", saying: "that game where you have to put limbs in certain places" },
  { author: "Tomasz", saying: "Utter buzzword bollocks" },
  { author: "Nick L", saying: "can’t you see my crab" },
  { author: "Ben D", saying: "like being stamped to death by mammoths" },
  { author: "Nick L", saying: "no lobsters in the library" },
  { author: "Chris L", saying: "it’s a beast and it’s only just been born" },
  { author: "Thibaud", saying: "I just need to move to California" },
  { author: "Ben D", saying: "cross repository blob mount" },
  { author: "Abigail", saying: "I am a secret wizard" },
  { author: "Ben D", saying: "near the back of the kama sutra, that one" },
  { author: "Todd", saying: "everything is a blob" },
  { author: "Chris L", saying: "Bay Rans" },
  { author: "Tomasz", saying: "shark onesie is fine" },
  { author: "Nick L", saying: "wouldn’t worry, it does sometimes do weird things" },
  { author: "Tomasz", saying: "is it supposed to be satanist somehow?" },
  { author: "Chris L", saying: "I am the docs" },
  { author: "Chris L", saying: "told the whale to piss off and now fan is back to normal" },
  { author: "Chris L", saying: "as if a whale could swim with 6 shipping containers on it" },
  { author: "Colin", saying: "in the 1950s, the most popular type of banana was called big mike" },
  { author: "Nick L", saying: "always have a bow and arrow handy" },
  { author: "Nick L", saying: "pretty sure you’ve always been dead" },
  { author: "Chris L", saying: "on the zinsser" },
  { author: "Chris L", saying: "couple of zinssers" },
  { author: "Chris L", saying: "charge it through the nose" },
  { author: "Chris L", saying: "seed sensations is a quality loaf" },
  { author: "Chris L", saying: "might have a raz" },
  { author: "Nick L", saying: "I’m getting distracted by the smells" },
  { author: "Chris L", saying: "maybe I should just stop squashing" },
  { author: "Nick L", saying: "need detective pikachu" },
  { author: "Ben D", saying: "I’m shit at this but I’m not that shit" },
  { author: "Steve S", saying: "I deleted the repo so no one has any issues" },
  { author: "Nick L", saying: "plugged into the pineaptrix" },
  { author: "Chris L", saying: "what is that fatty gap about" },
  { author: "Chris L", saying: "Is it linting itself" },
  { author: "Chris L", saying: "I miss seeing all the variables" },
  { author: "Nick L", saying: "not seeing any kittens" },
  { author: "Tomasz", saying: "you owe me a cobra" },
  { author: "Steve S", saying: "I've had 5 amazing seizures this morning" },
  { author: "Chris L", saying: "just lob it all in a zorb" },
  { author: "Nick L", saying: "I’ll do it kneeless" },
  { author: "Chris L", saying: "can you not just behead the bird?" },
  { author: "Ben D", saying: "hunt and peck with one hand was faster" },
  { author: "Todd", saying: "somewhere it has to be deanonamisable" },
  { author: "Nick L", saying: "chief of conflict resolution" },
  { author: "Nick L", saying: "I’m head of headshots mate" },
  { author: "Simon", saying: "I’ll just get my sloth out" },
  { author: "Will B", saying: "If you love something, <strike>set it free</strike> deploy it on friday" },
  { author: "Ben D", saying: "I'm really looking to forward to trying to work out whether cameron is talking about thibaud or tibor" },
  { author: "Nick L", saying: "the borbonator" },
  { author: "Chris L", saying: "just whack some LEDs in the nana’s" },
  { author: "Chris L", saying: "does everything get it’s own zorb?" },
  { author: "Nick L", saying: "bourbon api only works with html" },
  { author: "Nick L", saying: "flown in via stork express" },
  { author: "Nick L", saying: "tactical pre-main puke" },
  { author: "Nick L", saying: "might accidentally bath the dj instead of the bird though" },
  { author: "Nick L", saying: "Chris loves a little sausage" },
  { author: "Nick L", saying: "I don’t think I’m functioning" },
  { author: "Nick L", saying: "magic sometimes has odd side effects" },
  { author: "Chris L", saying: "polyfill with cheese" },
  { author: "Chris L", saying: "get a lamp on it" },
  { author: "Chris L", saying: "woff woff" },
  { author: "Chris L", saying: "I just answer ‘egg’ to every question" },
  { author: "Thibaud", saying: "Oh, what I have done..." },
  { author: "Simon", saying: "it’s 250 lines of filth" },
  { author: "Nick L", saying: "best make them biteproof" },
  { author: "Nick L", saying: "Deirdre wants to see Alan’s large marrow" },
  { author: "Chris L", saying: "djyagtail" },
  { author: "Chris L", saying: "imagine being 300 years old" },
  { author: "Nick L", saying: "don’t want my bore hole running dry" },
  { author: "Nick L", saying: "would you like to vasaline his ears" },
  { author: "Nick L", saying: "right in the bhaji" },
  { author: "Chris L", saying: "they were eating it, getting wired and causing mayhem" },
  { author: "Chris L", saying: "sounded like I was in a foam sandwich" },
  { author: "Ben D", saying: "available in 'goth jizz burst'" },
  { author: "Nick L", saying: "it’s like two components, but with the same component twice inside" },
  { author: "Ben D", saying: "I’ve always had a good guitar gurn" },
  { author: "Ben D", saying: "like a bulldog eating wasps" },
  { author: "Chris L", saying: "did she pull out her oboe" },
  { author: "Will B", saying: "there's a bowl of crunch at the end for sure" },
  { author: "Chris L", saying: "house full of sheep" },
  { author: "Nick L", saying: "lord of the sprinkles" },
  { author: "Nick L", saying: "looking after your pastries" },
  { author: "Simon", saying: "if you clean a vacuum cleaner, you become a vacuum cleaner" },
  { author: "Nick L", saying: "deep nosing" },
  { author: "Nick L", saying: "is he refactoring his house into react" },
  { author: "Tomasz", saying: "she'll have you for breakfast" },
  { author: "Jane", saying: "I’m very limbic today" },
  { author: "Ben D", saying: "don't believe everything you think - believe everything jeff bezos thinks" },
  { author: "Jenny H", saying: "muscle is where the meat is" },
  { author: "Todd", saying: "feed their documentation fetish" },
  { author: "Ben D", saying: "I admire the shit out of it" },
  { author: "Ben D", saying: "Obviously I’m not a mother but I am a twin" },
  { author: "Will B", saying: "I'm trending" },
  { author: "Will B", saying: "I'll merge anything" },
  { author: "Nick L", saying: "gimp suit for your roof" },
  { author: "Tomasz", saying: "I've had some wine you can tell" },
  { author: "Nick L", saying: "did you not do it in Russian?" },
  { author: "Will B", saying: "You've got a level 2 poltergeist" },
  { author: "Nick L", saying: "printing heroku" },
  { author: "Nick L", saying: "I’ll release some snakes" },
  { author: "Chris L", saying: "even the can looks edible" },
  { author: "Ben D", saying: "syncopate 'til you herniate" },
  { author: "Nick L", saying: "I see your toaster matches your bike" },
  { author: "Chris L", saying: "they need to make more things in lichen green" },
  { author: "Steve S", saying: "Bean there done that" },
  { author: "Nick L", saying: "think it depends on your ears" },
  { author: "Chris L", saying: "what other animals are in dev that i don’t know about" },
  { author: "Chris L", saying: "the sprint sloth" },
  { author: "Chris L", saying: "the backlog bear" },
  { author: "Steve S", saying: "A portal will open up in my kitchen and I'll get to ascend into nugget utopia" },
  { author: "Tomasz", saying: "I think software should ask you to opt into the banter." },
  { author: "Nick L", saying: "only a grand for an erection" },
  { author: "Simon", saying: "are you going round squeezing lots of wood" },
  { author: "Simon", saying: "can’t get enough lift from the ears" },
  { author: "Nick L", saying: "handy for catching door ticklers" },
  { author: "Simon", saying: "my ears start wtf’ing" },
  { author: "Will B", saying: "<code>$(fuck-that).upper()</code>" },
  { author: "Nick L", saying: "should have macaroned him in the face" },
  { author: "Steve S", saying: "My gangly fingers don’t work like they used to" },
  { author: "Chris L", saying: "the robot is acceptable" },
  { author: "Simon", saying: "like waking up in a hot bag" },
  { author: "Nick L", saying: "the humanwillbapeed" },
  { author: "Will B", saying: "I got munched" },
  { author: "Nick L", saying: "just switch the switch behind your right ear" },
  { author: "Chris L", saying: "use it as a mini foot-tickling window" },
  { author: "Will B", saying: "There's nothing he can't do with a pint in his right and his keyboard in his left" },
  { author: "Tomasz", saying: "its a bit like olives, takes time to like them" },
  { author: "Chris L", saying: "crouching tiger hidden cow" },
  { author: "Chris L", saying: "you’re basically doing a tour of my life" },
  { author: "Tomasz", saying: "I don't understand what you are doing here but if it feels right." },
  { author: "Chris L", saying: "cloudy with a chance of tables" },
  { author: "Chris L", saying: "wish my fingers were made from bournville" },
  { author: "Chris L", saying: "I charge randomly" },
  { author: "Chris L", saying: "release the hounds!" },
  { author: "Will B", saying: "Resto in pesto" },
  { author: "Tomasz", saying: "you cant possibly satisfy me" },
  { author: "Nick L", saying: "it makes my right arm twitch when I hit my brain" },
  { author: "Will B", saying: "I'm a one man party" },
  { author: "Chris L", saying: "fast track to the biscuit window" },
  { author: "Tomasz", saying: "dont sarcasm me at this time" },
  { author: "Chris L", saying: "do paws work on touch id" },
  { author: "Steve S", saying: "it was like walking on chicken soup bouillon" },
  { author: "Steve S", saying: "It's like you’re trying to build a house in the forest and there's a chainsaw in the next shed over that you could use if you want" },
  { author: "Will B", saying: "I will be craving death after it" },
  { author: "Chris L", saying: "this fork seems alright" },
  { author: "Tomasz", saying: "do I look like a google expert to you" },
  { author: "Nick L", saying: "just smear it all over your body and see what parts get numb" },
  { author: "Nick L", saying: "the condescending operator does it for you" },
  { author: "Nick L", saying: "are you going to be my Todd" },
  { author: "Paul B", saying: "I'd love to do a roast potato tasting menu" },
  { author: "Tomasz", saying: "I've been doing a lot of self-inflicted DRF" },
  { author: "Nick L", saying: "didn’t get a chance to leech him" },
  { author: "Will B", saying: "I am the long purple brick in this game of Tetris" },
  { author: "Will B", saying: "Wanna hang out the back of my rocket" },
  { author: "Ben D", saying: "I think in his hands a spade with some dental floss on it would rip" },
  { author: "Will B", saying: "I want more beans" },
  { author: "Nick L", saying: "alexa hide me from the foxes" },
  { author: "Chris L", saying: "I’ll go bonkers on conkers" },
  { author: "Chris L", saying: "is it a festival, a coffee or a cheese?" },
  { author: "Chris L", saying: "why is it this complex labyrinth of tick boxes and magical lingo" },
  { author: "Mitch", saying: "Wizards are difficult" },
  { author: "Nick L", saying: "woodpecker on the nuts" },
  { author: "Nick L", saying: "the hunchback of bude" },
  { author: "Simon", saying: "what is a hot deaker" },
  { author: "Steve S", saying: "nothing useful from me" },
  { author: "Simon", saying: "ostrich is best" },
  { author: "Olly W", saying: "karma jackpot" },
  { author: "Chris L", saying: "in trenchard I trod on a strongbow can with a knob straw in it" },
  { author: "Josh", saying: "I always appreciate succulent lattice feedback" },
  { author: "Nick L", saying: "hairy mic" },
  { author: "Chris L", saying: "Its sweated on itself" },
  { author: "Nick L", saying: "takes a lot of skill to poke two things in at once, one in the top and one of the bottom ones simultaneously" },
  { author: "Chris L", saying: "he could buy a cow" },
  { author: "Chris L", saying: "simon's developer nightmares" },
  { author: "Alex B", saying: "might just comment out the whole repo and go on sabbatical" },
  { author: "Nick L", saying: "warm front cold back" },
  { author: "Mel", saying: "don't yeet ur cat" },
  { author: "Chris L", saying: "end up in kebab-u-like at 3am" },
  { author: "Ben D", saying: "very 'fingery'" },
  { author: "Chris L", saying: "fastest finger first" },
  { author: "Chris L", saying: "would be a big bird on a 5xl" },
  { author: "Nick L", saying: "what's with the fingering" },
  { author: "Ellie", saying: "it gives my canoncial data preferences the absolute ick" },
  { author: "Nick L", saying: "maybe I should hook up all of the farmers cows" },
  { author: "Ben D", saying: "caffeinate then commiserate" },
  { author: "Ben D", saying: "I don't really care how the sausage is made" },
  { author: "Nick L", saying: "head of furry boom" },
  { author: "Chris L", saying: "mow the roof" },
  { author: "Simon", saying: "my trackpad is moist" },
  { author: "Steve S", saying: "I'd have the michael buble playing so loud that you'll never sleep again" },
  { author: "Chris L", saying: "you’ll find nemo in seconds" },
  { author: "Thibaud", saying: "It’s crazy how much more you can do in the summer with effective cooling" },
  { author: "Ben D", saying: "I love that pre-rain smell" },
  { author: "Simon", saying: "nothing like a bit of scouse lamination" },
  { author: "Simon", saying: "who needs the lotto when you can just steal shit" },
  { author: "James H", saying: "I could be a whisk, because I like to mix things up" },
  { author: "James H", saying: "You’ve got a lot of range with kitchen utensils" },
  { author: "Nick L", saying: "get in his tiger moth and machine gun the fuck out of you" },
  { author: "Will B", saying: "I will always disco" },
  { author: "Will B", saying: "you can put a beer in your kanga pouch and wiggle" },
  { author: "Kev", saying: "up to my nuts in spice" },
  { author: "Chris L", saying: "do you ever pre-heat your office?" },
  { author: "Chris L", saying: "where’s the turkey?" },
  { author: "Steve S", saying: "tastes like liquid summer" },
  { author: "Steve S", saying: "they call me the tong king" },
  { author: "Chris L", saying: "have a bath with the loch ness monster" },
  { author: "Thibaud", saying: "it took me a few years but I know what G&T means now" },
  { author: "Dan B", saying: "I don’t have the capacity to be curious right now" },
  { author: "Chris L", saying: "I breathe triple A mate" },
  { author: "Helen C", saying: "If it’s not warm and furry and farting it can’t recreate the real experience…" },
  { author: "Chris L", saying: "I’m yet to tickle its tummy" },
  { author: "Nick L", saying: "are they canine crypto investors" },
  { author: "Chris L", saying: "mine a million then go for a margherita" },
  { author: "Will B", saying: "I want Jacob's Owl" },
  { author: "Will B", saying: "I need high ceilings and street wine" },
  { author: "Tomasz", saying: "Jesus Christ on a bendy bus!" },
  { author: "Nick L", saying: "Torchbox need to start paying for ear massages" },
  { author: "Chris L", saying: "I just want to write code and eat pringles" },
  { author: "Steve S", saying: "We are trying to collect 2 of every animal for this project" },
  { author: "Dan B", saying: "we had a funky Heisenbug on Upshot" },
  { author: "Dan B", saying: "Patsy != Lucy" },
  { author: "Kev", saying: "It was like walking through a headache" },
  { author: "Nick L", saying: "the goat is especially bad" },
  { author: "Chris L", saying: "now there’s fingers in all sorts of pies" },
  { author: "Chris L", saying: "as Celine Dion once said it’s all coming back to me" },
  { author: "Ellie", saying: "I'm a hand talker" },
  { author: "Steve S", saying: "My diet is vegetable and sadness" },
  { author: "Tomasz", saying: "Can't get more meaty meat than that" },
  { author: "Simon", saying: "air fryer shrine" },
  { author: "Dan B", saying: "there's beauty in both" },
  { author: "Chris L", saying: "get tanned like a barcode" },
  { author: "Tomasz", saying: "Acknowledging that we're not shit might be a good idea" },
  { author: "Simon", saying: "I’d need to see the curlies" },
  { author: "Will B", saying: "I just want to lift maxes and avoid taxes" },
  { author: "Ben E", saying: "There should always be a little sun" },
  { author: "Simon", saying: "I call it the house of pain" },
  { author: "Simon", saying: "smashing back the jam" },
  { author: "Chris L", saying: "need a sober comparison" },
  { author: "Chris L", saying: "deliciouszone" },
  { author: "Chris L", saying: "napping in the starter" },
  { author: "Tomasz", saying: "I love controversy. I love everyone." },
  { author: "Steve S", saying: "I've never understood vests" },
  { author: "Ben D", saying: "he really is the zach braff of prog" },
  { author: "Simon", saying: "how can you eat katsu sauce without cutlery" },
  { author: "Anna P", saying: "we've got bigger potatoes" },
  { author: "Nick L", saying: "Stone Cold Steve in Austin" },
  { author: "Ben D", saying: "I would love to see a dog headbanging in 13/8" },
  { author: "Simon", saying: "all beer no pram" },
  { author: "Chris L", saying: "sausage infused shorts" },
  { author: "Will B", saying: "You can be my Brótogé" },
  { author: "Chris L", saying: "free shower tickles" },
  { author: "Nick L", saying: "2 soft closing, then 1 shocker" },
  { author: "Nick L", saying: "my elephant game is awesome" },
  { author: "Chris L", saying: "prepare for lamination" },
  { author: "Simon", saying: "npm install thibaud" },
  { author: "Chris L", saying: "death by dentures" },
  { author: "Simon", saying: "all disco no design" },
  { author: "Chris L", saying: "ear hoovers" },
  { author: "Jo F", saying: "Shout if you need extra poking" },
  { author: "Simon", saying: "imagine a 5k deer" },
  { author: "Chris L", saying: "WA5TAIL" },
  { author: "Helen W", saying: "We should all be branded with the flame" },
  { author: "Tomasz", saying: "this is some another level of softboi poetry going on here" },
  { author: "Steve S", saying: "you were in my dream last night" },
  { author: "Alex B", saying: "centralising the forks" },
  { author: "Steve S", saying: "I could taco bout tacos all day" },
  { author: "Simon", saying: "I need to try wood" },
  { author: "Joe H", saying: "These are from my big cave of collected goodness" },
  { author: "pv", saying: "All mouth and no trousers" },
  { author: "pv", saying: "well shit in a bag and punch it" },
  { author: "pv", saying: "if your aunty had balls she'd be your uncle" },
  { author: "Will B", saying: "It’s the same thing as anything" },
  { author: "Joe H", saying: "Laziness is the favourite of all my defaults" },
  { author: "Chris L", saying: "another day another div" },
  { author: "Simon", saying: "accessibility overlord jane™" },
  { author: "Will B", saying: "Soy Beta dev" },
  { author: "Tomasz", saying: "Japanese-dead-people-at-home kind of shrine" },
  { author: "Nick L", saying: "scrub me baby" },
  { author: "Chris L", saying: "dance floor full of molars" },
  { author: "Will B", saying: "my demons are funny" },
  { author: "Tom U", saying: "From now on I am only changing DNS records if I can get 11 people to watch me" },
  { author: "Ben D", saying: "I feel the fusion lust rising within me" },
  { author: "Chris L", saying: "it’ll be bats in a tropical rainforest tonight" },
  { author: "Helen W", saying: "My bored is bored" },
  { author: "Nick S", saying: "You're a simple man, Simon" },
  { author: "Cassidy", saying: "have to love a man that loves pineapples" },
  { author: "Simon", saying: "there’s just no going back from cat piss" },
  { author: "Dan B", saying: "I graduate every day" },
  { author: "Chris L", saying: "who leaks out of their nose when they’re sleepy" },
  { author: "Dan B", saying: "I know enough to be dangerous" },
  { author: "Chris S", saying: "chmod 007" },
  { author: "Joe H", saying: "Acey bongo!" },
  { author: "Simon", saying: "base64 encoded the fuck out of everything" },
  { author: "Joe H", saying: "Dip me in your Monday milk" },
  { author: "Andrew WS", saying: "Fear is a great motivator" },
  { author: "Kev", saying: "It's like an un-sponsored roundabout" },
  { author: "Tom U", saying: "maybe I just sound too much like an air conditioner" },
  { author: "Will B", saying: "It’s Britney bitch" },
  { author: "pv", saying: "Mainlining the nuts" },
  { author: "Nick L", saying: "free kipper with every estimate" },
  { author: "Ben D", saying: "I think it's just normal dread" },
  { author: "Ben D", saying: "webpack is awesome, but webpack is fucking heinous" },
  { author: "Chris L", saying: "we’re just spawning bugs" },
  { author: "Will B", saying: "Big dogs can't join the rat race" },
  { author: "Will B", saying: "I am filled with whimsy" },
  { author: "Chris L", saying: "he smelt like arson" },
  { author: "Will B", saying: "Physically, I'm here. Mentally, I am Christmas." },
  { author: "Will B", saying: "Somewhere between a nap and 6 pints" },
  { author: "Simon", saying: "processprocess <i>process</i> <b>process PROCESS</b>" },
  { author: "Will B", saying: "I just want a meal deal and a vape" },
  { author: "Will B", saying: "Someone get him a gavel" },
  { author: "Nick L", saying: "you’d want some kind of nut detector" },
  { author: "Joe H", saying: "Preamble ramble" },
  { author: "Joe H", saying: "I've got a bee in my bonnet about the reports, not a bad bee, just a bee" },
  { author: "Ben D", saying: "don't discount the dog" },
  { author: "Dan B", saying: "prepare for the customary cringe" },
  { author: "Nick L", saying: "I’ll do an iron lotus for you" },
  { author: "Nick L", saying: "Elon Musk in a box" },
  { author: "Anna P", saying: "Like a chickenpox party" },
  { author: "Chris L", saying: "a slightly ripened dairylea" },
  { author: "Nick L", saying: "is he dripping in butter" },
  { author: "Kev", saying: "I KNEW it would be airports" },
  { author: "Chris L", saying: "espresso through the hosepipe" },
  { author: "Tomasz", saying: "I like drinking with my grandma" },
  { author: "Simon", saying: "my fingers have forgotten" },
  { author: "Nick L", saying: "want to join a zoom and watch me do nordschleife?" },
  { author: "pv", saying: "I’ve often been called an opinionated asset" },
  { author: "Steve S", saying: "I do the best bug fixes in my sleep" },
  { author: "Anna P", saying: "its all gravy on this train" },
  { author: "Nick L", saying: "my middle knob doesn’t work" },
  { author: "Chris L", saying: "then everyone spoke like chipmunks" },
  { author: "Will B", saying: "I wish I was your cats" },
  { author: "Anna P", saying: "there’s only so many flapjacks i can eat today" },
  { author: "Anon", saying: "That – I won’t give my opinion on that but we’ll get there one day" },
  { author: "Chris L", saying: "how do you restart the whales engine" },
  { author: "Lauren", saying: "anything from bodies under the patio to weaving jumpers out of cat hair" },
  { author: "James H", saying: "There are some scripts happening" },
  { author: "Simon", saying: "just banter and vibes" },
  { author: "Thibaud", saying: "Wagtail is big" },
  { author: "Chris L", saying: "had to detach my head to go back in time" },
  { author: "Chris L", saying: "he’s too busy with his threadpoolexecutor" },
  { author: "Steve S", saying: "it's all fun and games until deployment" },
  { author: "Steve S", saying: "our old is your new" },
  { author: "Chris L", saying: "thaw me out when it’s time for refinement" },
  { author: "Simon", saying: "I can hear them sponging outside my room" },
  { author: "Nick L", saying: "they’re still stuck in there weeing on your walls" },
  { author: "Chris L", saying: "backlog refinement in the bearpit" },
  { author: "Simon", saying: "they go mad when I pull out the hotdogs" },
  { author: "Nick L", saying: "I just had to catch a pheasant" },
  { author: "Chris L", saying: "time for a prune" },
  { author: "Nick L", saying: "wonder how big the glitter poo will be if i base64 encode it" },
  { author: "Chris D", saying: "I'm used to being the fun killer these days" },
  { author: "Ben D", saying: "it’s the right kind of unhinged" },
  { author: "Ben D", saying: "no-one's arguing with those calves" },
  { author: "Mark", saying: "they don’t have a strategy so don’t expect any logic" },
  { author: "Charmagne", saying: "I’d totally hands down win a rap-off" },
  { author: "Kev", saying: "I can send you a pregnant cow, or some yoghurts" },
  { author: "Kev", saying: "I've been eating yoghurts all day" },
  { author: "Mark", saying: "I’ve opened the agency bullshit dictionary" },
  { author: "Simon", saying: "thank god for danks" },
  { author: "Simon", saying: "hey look how much money you’ve spunked up the wall with third party GTM" },
  { author: "Chris L", saying: "share your lynx africa with loch ness" },
  { author: "Simon", saying: "the bhaji is always inconsistent" },
  { author: "Ian", saying: "Ten days of Nick Lee would rock anybody's world" },
  { author: "Chris L", saying: "it's a cherry pickers delight" },
  { author: "Kev", saying: "I couldn't CEO a cat" },
  { author: "Helen C", saying: "I tell my husband off for being rude to alexa" },
  { author: "Kev", saying: "I'm usually 90% sense free" },
  { author: "Arran", saying: "I don’t like being out after 2pm on a Sunday" },
  { author: "Mark", saying: "going to live amongst the kangaroos" },
  { author: "Kev", saying: "sso good" },
  { author: "Nick L", saying: "so many anonymous otters" },
  { author: "Nick L", saying: "the otter is going wild" },
  { author: "Jenny H", saying: "It's a KitKat Chunky and it goes right in" },
  { author: "Simon", saying: "bread on toast" },
  { author: "Simon", saying: "my whole house is vibrating again" },
  { author: "Katriina", saying: "I’m a silly person with small hands and a big phone" },
  { author: "Joe H", saying: "Have a break, have a quick cat." },
  { author: "Chris L", saying: "may as well be eating cardboard for every meal" },
  { author: "Chris L", saying: "proper shoehorner" },
  { author: "Abigail", saying: "Paul Vetch special" },
  { author: "Mandy", saying: "Everyone you speak to is like an exhausted pigeon" },
  { author: "Nick L", saying: "attach a defensive skunk to the package" },
  { author: "Simon", saying: "remember it's just pixels on a screen, no one really gives a shit" },
  { author: "Josh", saying: "they don't call me quick-draw mcmoji for nothing" },
  { author: "Anon", saying: "It’s cognitive tennis" },
  { author: "Helen C", saying: "Oh, I thought my cursor was your cursor. Mi cursor su cursor." },
  { author: "Simon", saying: "Now That's What I Call MegaBiscuit™ 2024" },
  { author: "Cassie", saying: "hi I'm here for the donuts" },
  { author: "Thibaud", saying: "It’s just another spreadsheet with words in it" },
  { author: "Arran", saying: "He should run 'how not to be a shit client' classes" },
  { author: "Peter H", saying: "I might need to start a cult as a side hustle" },
  { author: "Baptiste", saying: "Come on, they're paying me in brown cheese it's worth it" },
  { author: "John D", saying: "Real Housewives Of Torchbox" },
  { author: "Pete W", saying: "React doesn't do things when you tell it to, it does things when it feels like it" },
  { author: "John D", saying: "Nesting dolls of certainty" },
  { author: "Arran", saying: "Tentative naughty list" },
  { author: "Peter H", saying: "Hoang on" },
  { author: "Vicky", saying: "His priorities are a moveable feast" },
  { author: "Chris L", saying: "just turn all your servers off" },
  { author: "Mandy", saying: "Who even are we?" },
  { author: "Ania", saying: "i dont even know which way to bite it" },
  { author: "Josh", saying: "the mustard tiger always improves my day" },
  { author: "Mandy", saying: "Like a hot potato!" },
  { author: "Josh", saying: "It's like Brian Eno if he got high and watched 2001" },
  { author: "Nick L", saying: "obviously it depends on girth" },
  { author: "Rachel", saying: "That's the context crab" },
  { author: "Iona", saying: "it’s a juicy war zone" },
  { author: "Chris L", saying: "sausage roll sweetener" },
  { author: "John D", saying: "From regression to aggression" },
  { author: "Simon", saying: "run off clutching my woffs" },
  { author: "Mandy", saying: "Costa del Derbyshire" },
  { author: "Mark", saying: "need to sit down with a bottle of rum and a spreadsheet" },
  { author: "Alice", saying: "they call me Alice Wise Logan" },
  { author: "Chris L", saying: "half rice half chips" },
  { author: "Charmagne", saying: "Extra points for a giant trunk" },
  { author: "John D", saying: "Is it draughts or 3d chess?" },
  { author: "Josh", saying: "hang on, let me zoom to 300%" },
  { author: "Charmagne", saying: "He looks like a wormer to me" },
  { author: "Alice", saying: "a real scoffer" },
  { author: "Mitch", saying: "just undo everything" },
  { author: "Phil M", saying: "Dreams come at a cost" },
  { author: "John D", saying: "I don't want to live in a sweaty Lush" },
  { author: "Josh", saying: "prepare for an onslaught of ego-driven development" },
  { author: "Weylon", saying: "I’m just budget friendly" },
  { author: "Chris H", saying: "I’d rather have dead rats and heating" },
  { author: "Mandy", saying: "Very mondayish" },
  { author: "Mark", saying: "digging deep to remember why I live in the uk" },
  { author: "Mitch", saying: "Drive to Spain" },
  { author: "Simon", saying: "I'm dumb but not that dumb" },
  { author: "Chris L", saying: "your head my shoulders" },
  { author: "Lizzie", saying: "Life’s too short for bad food decisions" },
  { author: "Alice", saying: "this is not the last time I will be weird" },
  { author: "Simon", saying: "I'm too scared to tinker" },
  { author: "Ben T", saying: "in the armpit of the star" },
  { author: "Dave H", saying: "Late Night Tales with Dave Harris" },
  { author: "Ben E", saying: "bedtime snuggles with the OG paddington bear" },
  { author: "Simon", saying: "I can be destroyer of worlds" },
  { author: "Steve S", saying: "I'll play it on tin whistle standing by the glow of a golden bowl of soup" },
  { author: "Ellie", saying: "surthriving" },
  { author: "Chris L", saying: "I think the level of ranting is equivalent to the level of how preposterous that suggestion is" },
  { author: "Simon", saying: "I want to drown them in data" },
  { author: "Kev", saying: "feels like I'm carrying a birds nest on my face" },
  { author: "Nick L", saying: "i can’t get it to use my proper pigeon" },
  { author: "Ania", saying: "the thicker the more IQ, you know it" },
  { author: "pv", saying: "they have completely screwed the pooch" },
  { author: "Chris L", saying: "Stone Cold Steve Steinwand" },
  { author: "Mark", saying: "spiritually i’ve been mauled" },
  { author: "Nick L", saying: "cellotape a dog to it" },
  { author: "Dom", saying: "I live for the berrocas" },
  { author: "Dom", saying: "the orange ambulance" },
  { author: "Mitch", saying: "I have the memory of a bird so it didn’t happen." },
  { author: "Maciej", saying: "looking forward to having my own claude code goose" },
  { author: "Claudia", saying: "you can call me the butcher" },
  { author: "Ellie", saying: "Not as good as Miles's ginormous spanner" },
  { author: "Chris L", saying: "i was just blasting arrows down the alley" },
  { author: "Bojan", saying: "I almost deleted my computer" },
  { author: "Nick L", saying: "why would I croissant a new employee" },
  { author: "Josh", saying: "Sometimes you do all the right things and the mould still wins" },
  { author: "Mitch", saying: "I am the flex" },
  { author: "Nick L", saying: "stomach feels dangerous" },
  { author: "Simon", saying: "your wood will be swollen" },
  { author: "Chris L", saying: "need to get some drones to fly them into their mouths" },
  { author: "Phil M", saying: "Any soft fruits are welcome" },
  { author: "Helen C", saying: "Emperor PalpeopleHRpatine" },
  { author: "Anon", saying: "Staying alive in the data lake of chaos" },
  { author: "Mark", saying: "wake up in madagascar" },
  { author: "Roman", saying: "I’m bathing in vodka and baby oil after end of the day" },
  { author: "Ania", saying: "ARE YOU WEARING JUMPER????!!!!!!" },
  { author: "Simon", saying: "normalise the naps" },
  { author: "Nick L", saying: "kill two birds with one doctor" },
  { author: "Nick L", saying: "private toe toucher" },
  { author: "Chris L", saying: "4 minute brawl" },
  { author: "Josh", saying: "my memory is weird" },
  { author: "Nick L", saying: "butler in the carbon fibre buff" },
  { author: "Josh", saying: "wun hundo" },
  { author: "Millie", saying: "bullets are breakdowns" },
  { author: "Millie", saying: "I make the bread, to GET the bread" },
  { author: "Weylon", saying: "all the glory and none of the blame" },
  { author: "Kev", saying: "I'm in a rebase dungeon" },
  { author: "Phil M", saying: "John 'Horse Whisperer' Dunford" },
];
